[package]
name = "svurl-service"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdl = "3.0.0"
percent-encoding = "2.1.0"
regex = "1.5.4"
rocket = "0.5.0-rc.1"
uritemplate-next = "0.2.0"
